[package]
name = "repoad"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
clap = { version = "4.5.39", features = ["derive"] }
content_inspector = "0.2.4"
git2 = "0.20.2"
tempfile = "3.20.0"
walkdir = "2.5.0"
